# Generated by Django 4.2.4 on 2024-08-06 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='club',
        ),
        migrations.RemoveField(
            model_name='question',
            name='auteur',
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='annee',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='publication.club'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumnie_annuaire',
            name='promotion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='annuaire',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='projet',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='Categorie',
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('id_publication', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='publication.publication')),
            ],
        ),
        migrations.CreateModel(
            name='event_inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=255)),
                ('date_archivage', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/')),
                ('club', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Club', to='publication.club')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='themes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='publication.theme_recherche'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie', to='publication.categorie'),
        ),
    ]
