# Generated by Django 4.2.4 on 2024-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_remove_publication_club_remove_question_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe_recherche',
            name='axe_recherche',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='equipe_recherche',
            name='objectif',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='equipe_recherche',
            name='problematique',
            field=models.TextField(default=''),
        ),
    ]
