# Generated by Django 4.2.4 on 2024-08-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_equipe_recherche_axe_recherche_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande_partenariat',
            old_name='contact',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='demande_partenariat',
            old_name='description',
            new_name='websiteUrl',
        ),
        migrations.AddField(
            model_name='demande_partenariat',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande_partenariat',
            name='organisme',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande_partenariat',
            name='prenom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande_partenariat',
            name='profession',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande_partenariat',
            name='tailleOrganisme',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
