# Generated by Django 5.0.6 on 2024-08-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_rename_contact_demande_partenariat_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('sujet', models.CharField(max_length=255)),
                ('formateur', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='formation',
            name='id_formation',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='type',
        ),
        migrations.AddField(
            model_name='formation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='Planing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='publication.planing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planing',
            name='sessions',
            field=models.ManyToManyField(related_name='sessions', to='publication.session'),
        ),
    ]
