# Generated by Django 5.0.6 on 2024-08-22 20:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_module_formation_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('specialites', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='formation',
            name='Planing',
        ),
        migrations.RemoveField(
            model_name='planing',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='planing',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default='Aucune description fournie'),
        ),
        migrations.AddField(
            model_name='module',
            name='volume_horaire',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='competences',
            field=models.ManyToManyField(related_name='competences', to='publication.competence'),
        ),
        migrations.AddField(
            model_name='module',
            name='formateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='publication.formateur'),
            preserve_default=False,
        ),
    ]
