# Generated by Django 5.0.6 on 2024-08-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0009_remove_module_chapitres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='competences',
            field=models.ManyToManyField(related_name='competences', to='publication.competence'),
        ),
        migrations.AlterField(
            model_name='module',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='publication.formateur'),
        ),
    ]
