# Generated by Django 5.0.6 on 2024-08-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0010_alter_module_competences_alter_module_formateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formateur', to='publication.formateur'),
        ),
    ]
