# Generated by Django 5.0.6 on 2024-09-01 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0012_alter_publication_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='lieu',
            field=models.CharField(default='salle conférence', max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='visiteur',
            field=models.CharField(default='Pr Jalil BOUKHOBZA', max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='formateur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formateur', to='publication.formateur'),
        ),
    ]
