# Generated by Django 5.0.6 on 2024-09-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0013_publication_lieu_publication_visiteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='etat',
        ),
        migrations.CreateModel(
            name='Demande_Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisme', models.CharField(max_length=50, verbose_name='')),
                ('email', models.EmailField(max_length=254)),
                ('Numero_telephone', models.IntegerField(blank=True, null=True)),
                ('Nombre_participants', models.IntegerField(blank=True, null=True)),
                ('Formations', models.ManyToManyField(related_name='themes_devis', to='publication.theme_formation')),
            ],
        ),
    ]
