# Generated by Django 5.0.6 on 2024-09-06 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0014_remove_devis_etat_demande_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='demande_devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publication.demande_devis'),
        ),
    ]
