# Generated by Django 5.0.6 on 2024-07-02 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FablabInscriptionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('numero_immatriculation', models.CharField(max_length=20)),
                ('cycle_etude', models.CharField(choices=[('1CP', '1CP'), ('2CP', '2CP'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS'), ('OTHERS', 'OTHERS')], max_length=10)),
                ('outils_maitrise', models.TextField()),
                ('projet_relationavec', models.CharField(choices=[('PFE', 'P.F.E'), ('Formation Master', 'Formation Complémentaire (Master)'), ('FIE', 'F.I.E'), ('Doctorat', 'Doctorat'), ('Competition ESI', 'Compétition-ESI'), ('Autre', 'Autre')], max_length=100)),
                ('description_projet', models.TextField()),
                ('projet_type', models.CharField(choices=[('Individuel avec coach', 'Projet individuel avec coach'), ('Individuel sans coach', 'Projet individuel sans coach'), ('Équipe avec coach', "Projet d'équipe appartenant à un club avec coach"), ('Équipe sans coach', "Projet d'équipe appartenant à un club sans coach"), ('Initié par ESI en collaboration avec fablab', 'Projet initié par ESI en collaboration avec fablab')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id_piece', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('quantite_disponible', models.IntegerField(default=0)),
                ('etat', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFablab.category')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='DemandeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('numero_immatriculation', models.CharField(max_length=20)),
                ('quantite_empruntee', models.IntegerField(default=1)),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('cycle_etude', models.CharField(choices=[('1CP', '1CP'), ('2CP', '2CP'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS'), ('OTHERS', 'OTHERS')], max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('nombre_jours_emprunt', models.IntegerField(default=1)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFablab.piece')),
            ],
            options={
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.CreateModel(
            name='UserSavedPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFablab.piece')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'piece')},
            },
        ),
    ]
