# Generated by Django 5.0.3 on 2024-08-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFablab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fablabinscriptionutilisateur',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
