# Generated by Django 4.2.4 on 2024-08-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFablab', '0002_fablabinscriptionutilisateur_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandemateriel',
            name='utilisateur',
        ),
    ]
